Vagrant.configure(2) do |config|

  config.vm.network "public_network"
 
  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "ubuntu/precise64"
    webserver.vm.network "forwarded_port", guest: 80, host: 3232

    webserver.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../cookbooks"
      chef.roles_path = "../../roles"
      chef.data_bags_path = "../../data_bags"
      chef.environments_path = "../../environments"  
      chef.node_name = "web_server"
      chef.add_recipe "apache2::default"
    end
  end
  
end